name: Inference API code quality

# CINTENT >> MANUAL_TRIGGER
# on:
#   pull_request:
#     paths:
#       - "**"
on: [repository_dispatch, workflow_dispatch]

jobs:
  run_tests:
    # CINTENT >> CHANGE_VERSION
    # runs-on: ubuntu-20.04
    runs-on: ubuntu-latest
    steps:
      # CINTENT >> CHANGE_VERSION
      # - uses: actions/checkout@v2
      - uses: actions/checkout@v4

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@a606c80c34ec190c6a20dea33d6d58ddb6c4e0cc

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          # CINTENT >> CHANGE_VERSION
          # python-version: 3.8
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -e .[quality]
      - name: Make quality
        run: |
          make quality

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}